### ISSUE TITLE
Could you publish a binary for Win32 platform?

### ISSUE THREAD

**Issue by wmjordan** [danoli3/FreeImage#17]
Thank you for picking up this long abandoned project.
I'm not C++ programmer and I have trouble compiling the project to DLL.
Could you include a Win32 DLL file in the publish?

**Comment by wmjordan** [comment]
Well, by excluding some unused (for me) code files, I managed to compile a usable library for my project.

**Comment by danoli3** [comment]
Nice! Else you can find the binaries in the openframeworks libraries for
vs2022 on openframeworks/apothecary

https://github.com/openframeworks/apothecary/releases/tag/bleeding
